#!/data/user/0/com.termux/files/usr/bin/bash
function Coloring {
NC='\033[0m'
LRED='\033[1;31m'
LGREEN='\033[1;32m'
YELLOW='\033[1;33m'
PURPLE='\033[1;35m'
LBLUE='\033[1;36m'
}

# BANNER
banner() {
toilet "$(figlet "LEOSENVIP")" -f term --gay  | pv -qL 3000
toilet "  TELEGRAM CHANNEL LEOSENVIPSTORE  " -f term -F border --gay  | pv -qL 3000
}

clear
Coloring
banner
sleep 0.2

if [ -f $HOME/LEOSENVIP/skin ]; then
chmod +x $HOME/LEOSENVIP/skin
mv $HOME/LEOSENVIP/skin $PREFIX/bin
fi

function redirect {
toilet "   TOOL INSTALL DONE   " -f term -F border --gay  | pv -qL 3000

  count=0
  total=3
  start=`date +%s`
  while [ $count -lt $total ]
  do
    sleep 1 # this is work
    cur=`date +%s`
    count=$(( $count + 1 ))
    pd=$(( $count * 73 / $total ))
    runtime=$(( $cur-$start ))
    estremain=$(( ($runtime * $total / $count)-$runtime ))
    printf "\r%d.%d%% complete - est %d:%0.2d remaining\e[K" $(( $count*100/$total )) $(( ($count*1000/$total)%10)) $(( $estremain/60 )) $(( $estremain%60 ))
  done
  printf "\n"
if [ -f $HOME/LEOSENVIP/menuskin ]; then
chmod +x setup
chmod +x menuskin
chmod +x pakskin
./menuskin
fi
}
toilet " CHECKING INSTALL TOOL " -f term -F border --gay  | pv -qL 3000
echo -e "${LGREEN}Checking Required packages${NC}"
packages=("wget" "unzip" "zip" "pv" "figlet" "toilet" "vim" "curl" "rsync" "x11-repo" "qemu-system-i386" "qemu-user-i386")
for pkg in ${packages[@]}; do
is_pkg_installed=$(dpkg-query -W --showformat='${Status}
' ${pkg} | grep "install ok installed")
if [ "${is_pkg_installed}" == "install ok installed" ]; then
echo -e ${LGREEN}${pkg}${NC} is installed.
else [ "" = "${is_pkg_installed}" ];
echo -e "${LRED}No ${pkg}. Setting up ${pkg}.${NC}"
pkg install ${pkg} -y
fi
done
redirect
